// <auto-generated />
using System;
using EntityFrameworkCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameworkCore.Data.Migrations
{
    [DbContext(typeof(FootballLeageDbcontext))]
    [Migration("20240324143719_addingMoreTeams")]
    partial class addingMoreTeams
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityFrameworkCore.Domain.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Coachs");
                });

            modelBuilder.Entity("EntityFrameworkCore.Domain.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 3, 24, 14, 37, 16, 937, DateTimeKind.Unspecified).AddTicks(8910),
                            Name = "Tivoli Garden F.C."
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 3, 24, 14, 37, 16, 937, DateTimeKind.Unspecified).AddTicks(8925),
                            Name = "Waterhourse  F.C."
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 3, 24, 14, 37, 16, 937, DateTimeKind.Unspecified).AddTicks(8926),
                            Name = "Humble Lions F.C."
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 3, 24, 14, 37, 16, 937, DateTimeKind.Unspecified).AddTicks(8927),
                            Name = "Chelsea F.C."
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 3, 24, 14, 37, 16, 937, DateTimeKind.Unspecified).AddTicks(8929),
                            Name = "Real Madrid "
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 3, 24, 14, 37, 16, 937, DateTimeKind.Unspecified).AddTicks(8933),
                            Name = "Inter Milan"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 3, 24, 14, 37, 16, 937, DateTimeKind.Unspecified).AddTicks(8934),
                            Name = "Inter Miami"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 3, 24, 14, 37, 16, 937, DateTimeKind.Unspecified).AddTicks(8936),
                            Name = "Seba United"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
